<?php 
/* App schema generated on: 2011-11-14 22:52:13 : 1321307533*/
class AppSchema extends CakeSchema {
	var $name = 'App';

	var $file = 'schema_2.php';

	function before($event = array()) {
		return true;
	}

	function after($event = array()) {
	}

	var $cities = array(
		'id' => array('type' => 'integer', 'null' => false, 'default' => NULL, 'length' => 4, 'key' => 'primary'),
		'name' => array('type' => 'string', 'null' => true, 'default' => NULL, 'length' => 100, 'key' => 'index', 'collate' => 'utf8_general_ci', 'charset' => 'utf8'),
		'latitude' => array('type' => 'float', 'null' => true, 'default' => NULL),
		'longitude' => array('type' => 'float', 'null' => true, 'default' => NULL),
		'region_id' => array('type' => 'integer', 'null' => true, 'default' => NULL, 'key' => 'index'),
		'other_names' => array('type' => 'string', 'null' => true, 'default' => NULL, 'key' => 'index', 'collate' => 'utf8_general_ci', 'charset' => 'utf8'),
		'near_city_names' => array('type' => 'text', 'null' => true, 'default' => NULL, 'key' => 'index', 'collate' => 'utf8_general_ci', 'charset' => 'utf8'),
		'created' => array('type' => 'timestamp', 'null' => false, 'default' => 'CURRENT_TIMESTAMP'),
		'updated' => array('type' => 'datetime', 'null' => true, 'default' => NULL),
		'isvalidflag' => array('type' => 'integer', 'null' => false, 'default' => '0', 'length' => 2),
		'geofinfo' => array('type' => 'text', 'null' => false, 'default' => NULL, 'collate' => 'utf8_general_ci', 'charset' => 'utf8'),
		'nbmembersformap' => array('type' => 'integer', 'null' => false, 'default' => '0'),
		'selectable' => array('type' => 'boolean', 'null' => true, 'default' => '0'),
		'nbmembers' => array('type' => 'integer', 'null' => false, 'default' => '0'),
		'indexes' => array('PRIMARY' => array('column' => 'id', 'unique' => 1), 'idregion' => array('column' => 'region_id', 'unique' => 0), 'name' => array('column' => 'name', 'unique' => 0), 'other_names' => array('column' => 'other_names', 'unique' => 0), 'i_city_fulltext' => array('column' => array('name', 'other_names'), 'unique' => 0), 'near_city_names_fulltext' => array('column' => 'near_city_names', 'unique' => 0)),
		'tableParameters' => array('charset' => 'latin1', 'collate' => 'latin1_swedish_ci', 'engine' => 'MyISAM')
	);
	var $countries = array(
		'id' => array('type' => 'integer', 'null' => false, 'default' => NULL, 'length' => 4, 'key' => 'primary'),
		'name' => array('type' => 'string', 'null' => true, 'default' => NULL, 'length' => 50, 'key' => 'index', 'collate' => 'utf8_general_ci', 'charset' => 'utf8'),
		'regionopen' => array('type' => 'integer', 'null' => false, 'default' => '1', 'length' => 2),
		'members' => array('type' => 'integer', 'null' => true, 'default' => NULL),
		'hcworld_created' => array('type' => 'datetime', 'null' => true, 'default' => NULL),
		'idnation' => array('type' => 'integer', 'null' => true, 'default' => NULL),
		'idcapital' => array('type' => 'integer', 'null' => false, 'default' => '0'),
		'latitude' => array('type' => 'float', 'null' => true, 'default' => NULL),
		'longitude' => array('type' => 'float', 'null' => true, 'default' => NULL),
		'continent' => array('type' => 'integer', 'null' => true, 'default' => NULL),
		'flag' => array('type' => 'string', 'null' => true, 'default' => NULL, 'length' => 2, 'collate' => 'utf8_general_ci', 'charset' => 'utf8'),
		'spamindex' => array('type' => 'integer', 'null' => true, 'default' => NULL, 'length' => 5),
		'indexes' => array('PRIMARY' => array('column' => 'id', 'unique' => 1), 'name' => array('column' => 'name', 'unique' => 0)),
		'tableParameters' => array('charset' => 'utf8', 'collate' => 'utf8_general_ci', 'engine' => 'MyISAM')
	);
	var $members = array(
		'id' => array('type' => 'integer', 'null' => false, 'default' => NULL, 'key' => 'primary'),
		'country_id' => array('type' => 'integer', 'null' => false, 'default' => '0', 'length' => 2, 'key' => 'index'),
		'city_id' => array('type' => 'string', 'null' => true, 'default' => NULL, 'key' => 'index', 'collate' => 'utf8_general_ci', 'charset' => 'utf8'),
		'region' => array('type' => 'string', 'null' => true, 'default' => NULL, 'key' => 'index', 'collate' => 'utf8_general_ci', 'charset' => 'utf8'),
		'zip' => array('type' => 'string', 'null' => true, 'default' => NULL, 'collate' => 'utf8_general_ci', 'charset' => 'utf8'),
		'username' => array('type' => 'string', 'null' => false, 'default' => NULL, 'key' => 'index', 'collate' => 'utf8_general_ci', 'charset' => 'utf8'),
		'accepted' => array('type' => 'boolean', 'null' => true, 'default' => NULL),
		'city_volunteer' => array('type' => 'boolean', 'null' => true, 'default' => '0'),
		'region_volunteer' => array('type' => 'boolean', 'null' => true, 'default' => '0'),
		'country_volunteer' => array('type' => 'boolean', 'null' => true, 'default' => '0'),
		'birthday' => array('type' => 'date', 'null' => true, 'default' => NULL),
		'homepage' => array('type' => 'string', 'null' => true, 'default' => NULL, 'collate' => 'utf8_general_ci', 'charset' => 'utf8'),
		'photo' => array('type' => 'string', 'null' => true, 'default' => NULL, 'collate' => 'utf8_general_ci', 'charset' => 'utf8'),
		'homephone' => array('type' => 'string', 'null' => true, 'default' => NULL, 'collate' => 'utf8_general_ci', 'charset' => 'utf8'),
		'workphone' => array('type' => 'string', 'null' => true, 'default' => NULL, 'collate' => 'utf8_general_ci', 'charset' => 'utf8'),
		'mobilephone' => array('type' => 'string', 'null' => true, 'default' => NULL, 'collate' => 'utf8_general_ci', 'charset' => 'utf8'),
		'fax' => array('type' => 'string', 'null' => true, 'default' => NULL, 'collate' => 'utf8_general_ci', 'charset' => 'utf8'),
		'occupation' => array('type' => 'string', 'null' => true, 'default' => NULL, 'key' => 'index', 'collate' => 'utf8_general_ci', 'charset' => 'utf8'),
		'updates' => array('type' => 'boolean', 'null' => false, 'default' => '1'),
		'secstreet' => array('type' => 'string', 'null' => true, 'default' => NULL, 'collate' => 'utf8_general_ci', 'charset' => 'utf8'),
		'seccity' => array('type' => 'string', 'null' => true, 'default' => NULL, 'collate' => 'utf8_general_ci', 'charset' => 'utf8'),
		'secregion' => array('type' => 'string', 'null' => true, 'default' => NULL, 'collate' => 'utf8_general_ci', 'charset' => 'utf8'),
		'seczip' => array('type' => 'string', 'null' => true, 'default' => NULL, 'collate' => 'utf8_general_ci', 'charset' => 'utf8'),
		'seccountry' => array('type' => 'integer', 'null' => false, 'default' => '0', 'length' => 2),
		'secphone' => array('type' => 'string', 'null' => true, 'default' => NULL, 'collate' => 'utf8_general_ci', 'charset' => 'utf8'),
		'secinfo' => array('type' => 'string', 'null' => true, 'default' => NULL, 'collate' => 'utf8_general_ci', 'charset' => 'utf8'),
		'languages' => array('type' => 'string', 'null' => true, 'default' => NULL, 'key' => 'index', 'collate' => 'utf8_general_ci', 'charset' => 'utf8'),
		'hobbies' => array('type' => 'string', 'null' => true, 'default' => NULL, 'key' => 'index', 'collate' => 'utf8_general_ci', 'charset' => 'utf8'),
		'organizations' => array('type' => 'string', 'null' => true, 'default' => NULL, 'key' => 'index', 'collate' => 'utf8_general_ci', 'charset' => 'utf8'),
		'travels' => array('type' => 'text', 'null' => true, 'default' => NULL, 'key' => 'index', 'collate' => 'utf8_general_ci', 'charset' => 'utf8'),
		'plans' => array('type' => 'text', 'null' => true, 'default' => NULL, 'key' => 'index', 'collate' => 'utf8_general_ci', 'charset' => 'utf8'),
		'aboutmyself' => array('type' => 'text', 'null' => true, 'default' => NULL, 'key' => 'index', 'collate' => 'utf8_general_ci', 'charset' => 'utf8'),
		'accom' => array('type' => 'integer', 'null' => true, 'default' => NULL, 'length' => 2, 'key' => 'index'),
		'offershow' => array('type' => 'boolean', 'null' => true, 'default' => '0'),
		'offerdinner' => array('type' => 'boolean', 'null' => true, 'default' => '0'),
		'offerother' => array('type' => 'string', 'null' => true, 'default' => NULL, 'key' => 'index', 'collate' => 'utf8_general_ci', 'charset' => 'utf8'),
		'besttimes' => array('type' => 'string', 'null' => true, 'default' => NULL, 'collate' => 'utf8_general_ci', 'charset' => 'utf8'),
		'publictrans' => array('type' => 'string', 'null' => true, 'default' => NULL, 'collate' => 'utf8_general_ci', 'charset' => 'utf8'),
		'bigcities' => array('type' => 'string', 'null' => true, 'default' => NULL, 'key' => 'index', 'collate' => 'utf8_general_ci', 'charset' => 'utf8'),
		'attractions' => array('type' => 'string', 'null' => true, 'default' => NULL, 'key' => 'index', 'collate' => 'utf8_general_ci', 'charset' => 'utf8'),
		'withgbfriend' => array('type' => 'boolean', 'null' => true, 'default' => '0'),
		'withgrandpa' => array('type' => 'boolean', 'null' => true, 'default' => '0'),
		'withpar' => array('type' => 'boolean', 'null' => true, 'default' => '0'),
		'withsibs' => array('type' => 'boolean', 'null' => true, 'default' => '0'),
		'withop' => array('type' => 'boolean', 'null' => true, 'default' => '0'),
		'withalone' => array('type' => 'boolean', 'null' => true, 'default' => '0'),
		'garden' => array('type' => 'boolean', 'null' => true, 'default' => '0'),
		'spacefloor' => array('type' => 'boolean', 'null' => true, 'default' => '0'),
		'matress' => array('type' => 'boolean', 'null' => true, 'default' => '0'),
		'sofa' => array('type' => 'boolean', 'null' => true, 'default' => '0'),
		'bed' => array('type' => 'boolean', 'null' => true, 'default' => '0'),
		'ownroom' => array('type' => 'boolean', 'null' => true, 'default' => '0'),
		'sleepother' => array('type' => 'text', 'null' => true, 'default' => NULL, 'collate' => 'utf8_general_ci', 'charset' => 'utf8'),
		'bringtent' => array('type' => 'boolean', 'null' => true, 'default' => '0'),
		'bringmat' => array('type' => 'boolean', 'null' => true, 'default' => '0'),
		'bringsleep' => array('type' => 'boolean', 'null' => true, 'default' => '0'),
		'numberguest' => array('type' => 'integer', 'null' => true, 'default' => NULL, 'length' => 2, 'key' => 'index'),
		'staylength' => array('type' => 'integer', 'null' => true, 'default' => '0', 'length' => 2, 'key' => 'index'),
		'notifyshould' => array('type' => 'integer', 'null' => true, 'default' => '0', 'length' => 2, 'key' => 'index'),
		'notifymust' => array('type' => 'integer', 'null' => true, 'default' => '0', 'length' => 2, 'key' => 'index'),
		'callarrival' => array('type' => 'boolean', 'null' => true, 'default' => '0'),
		'callbetween1' => array('type' => 'integer', 'null' => true, 'default' => '0', 'length' => 4),
		'callbetween2' => array('type' => 'integer', 'null' => true, 'default' => '0', 'length' => 4),
		'nodrugs' => array('type' => 'boolean', 'null' => true, 'default' => '0'),
		'noalc' => array('type' => 'boolean', 'null' => true, 'default' => '0'),
		'payphone' => array('type' => 'boolean', 'null' => true, 'default' => '0'),
		'payfood' => array('type' => 'boolean', 'null' => true, 'default' => '0'),
		'dodishes' => array('type' => 'boolean', 'null' => true, 'default' => '0'),
		'restriother' => array('type' => 'string', 'null' => true, 'default' => NULL, 'collate' => 'utf8_general_ci', 'charset' => 'utf8'),
		'pets' => array('type' => 'string', 'null' => true, 'default' => NULL, 'key' => 'index', 'collate' => 'utf8_general_ci', 'charset' => 'utf8'),
		'othcom' => array('type' => 'string', 'null' => true, 'default' => NULL, 'key' => 'index', 'collate' => 'utf8_general_ci', 'charset' => 'utf8'),
		'feedback' => array('type' => 'string', 'null' => true, 'default' => NULL, 'collate' => 'utf8_general_ci', 'charset' => 'utf8'),
		'terms' => array('type' => 'boolean', 'null' => true, 'default' => NULL),
		'category' => array('type' => 'integer', 'null' => true, 'default' => NULL),
		'flags' => array('type' => 'string', 'null' => true, 'default' => NULL, 'collate' => 'utf8_general_ci', 'charset' => 'utf8'),
		'level' => array('type' => 'integer', 'null' => false, 'default' => '0', 'length' => 4),
		'hcnotes' => array('type' => 'text', 'null' => false, 'default' => NULL, 'collate' => 'utf8_general_ci', 'charset' => 'utf8'),
		'name' => array('type' => 'string', 'null' => true, 'default' => NULL, 'key' => 'index', 'collate' => 'utf8_general_ci', 'charset' => 'utf8'),
		'street' => array('type' => 'string', 'null' => true, 'default' => NULL, 'key' => 'index', 'collate' => 'utf8_general_ci', 'charset' => 'utf8'),
		'email' => array('type' => 'string', 'null' => true, 'default' => NULL, 'key' => 'index', 'collate' => 'utf8_general_ci', 'charset' => 'utf8'),
		'password' => array('type' => 'string', 'null' => false, 'default' => NULL, 'collate' => 'utf8_general_ci', 'charset' => 'utf8'),
		'secemail' => array('type' => 'string', 'null' => false, 'default' => NULL, 'collate' => 'utf8_general_ci', 'charset' => 'utf8'),
		'namehide' => array('type' => 'boolean', 'null' => true, 'default' => '0'),
		'streethide' => array('type' => 'boolean', 'null' => true, 'default' => '0'),
		'lastlogin' => array('type' => 'datetime', 'null' => false, 'default' => '0000-00-00 00:00:00', 'key' => 'index'),
		'ip' => array('type' => 'string', 'null' => false, 'length' => 15, 'collate' => 'utf8_general_ci', 'charset' => 'utf8'),
		'vol_teaser' => array('type' => 'string', 'null' => true, 'default' => NULL, 'collate' => 'utf8_general_ci', 'charset' => 'utf8'),
		'vol_contact_info' => array('type' => 'string', 'null' => true, 'default' => NULL, 'collate' => 'utf8_general_ci', 'charset' => 'utf8'),
		'vol_why' => array('type' => 'string', 'null' => true, 'default' => NULL, 'collate' => 'utf8_general_ci', 'charset' => 'utf8'),
		'vol_what' => array('type' => 'string', 'null' => true, 'default' => NULL, 'collate' => 'utf8_general_ci', 'charset' => 'utf8'),
		'vol_additional' => array('type' => 'string', 'null' => true, 'default' => NULL, 'collate' => 'utf8_general_ci', 'charset' => 'utf8'),
		'emailerror' => array('type' => 'string', 'null' => true, 'default' => NULL, 'collate' => 'utf8_general_ci', 'charset' => 'utf8'),
		'lastaccess' => array('type' => 'datetime', 'null' => true, 'default' => NULL),
		'latitude' => array('type' => 'float', 'null' => true, 'default' => NULL),
		'longitude' => array('type' => 'float', 'null' => true, 'default' => NULL),
		'chat_msn' => array('type' => 'string', 'null' => true, 'default' => NULL, 'key' => 'index', 'collate' => 'utf8_general_ci', 'charset' => 'utf8'),
		'chat_icq' => array('type' => 'string', 'null' => true, 'default' => NULL, 'collate' => 'utf8_general_ci', 'charset' => 'utf8'),
		'chat_yahoo' => array('type' => 'string', 'null' => true, 'default' => NULL, 'collate' => 'utf8_general_ci', 'charset' => 'utf8'),
		'chat_skype' => array('type' => 'string', 'null' => true, 'default' => NULL, 'key' => 'index', 'collate' => 'utf8_general_ci', 'charset' => 'utf8'),
		'chat_others' => array('type' => 'string', 'null' => true, 'default' => NULL, 'collate' => 'utf8_general_ci', 'charset' => 'utf8'),
		'chat_aol' => array('type' => 'string', 'null' => true, 'default' => NULL, 'collate' => 'utf8_general_ci', 'charset' => 'utf8'),
		'nbhost' => array('type' => 'integer', 'null' => false, 'default' => '0', 'length' => 2),
		'nbguest' => array('type' => 'integer', 'null' => false, 'default' => '0', 'length' => 2),
		'nbcomment' => array('type' => 'integer', 'null' => false, 'default' => '0', 'length' => 2),
		'visincity' => array('type' => 'boolean', 'null' => true, 'default' => '1'),
		'visinlocation' => array('type' => 'boolean', 'null' => true, 'default' => '1', 'key' => 'index'),
		'nbtrust' => array('type' => 'integer', 'null' => false, 'default' => '0', 'length' => 2),
		'idcity' => array('type' => 'integer', 'null' => false, 'default' => '0', 'length' => 4, 'key' => 'index'),
		'nbpspcheck' => array('type' => 'integer', 'null' => false, 'default' => '0', 'length' => 2),
		'lang_signup' => array('type' => 'string', 'null' => true, 'default' => NULL, 'collate' => 'utf8_general_ci', 'charset' => 'utf8'),
		'lang_last' => array('type' => 'string', 'null' => true, 'default' => NULL, 'collate' => 'utf8_general_ci', 'charset' => 'utf8'),
		'nbvisit' => array('type' => 'integer', 'null' => false, 'default' => '0', 'length' => 8),
		'nbvisittoday' => array('type' => 'integer', 'null' => false, 'default' => '0', 'length' => 8),
		'myvisitidlist' => array('type' => 'string', 'null' => true, 'default' => NULL, 'collate' => 'utf8_general_ci', 'charset' => 'utf8'),
		'nbofremindreceivedsincelastlog' => array('type' => 'integer', 'null' => false, 'default' => '0'),
		'nbofemailreceivedsincelastlog' => array('type' => 'integer', 'null' => false, 'default' => '0'),
		'toberemind' => array('type' => 'datetime', 'null' => true, 'default' => NULL),
		'attractions_updated' => array('type' => 'datetime', 'null' => false, 'default' => '0000-00-00 00:00:00'),
		'created' => array('type' => 'datetime', 'null' => true, 'default' => NULL),
		'updated' => array('type' => 'datetime', 'null' => true, 'default' => NULL),
		'indexes' => array('PRIMARY' => array('column' => 'id', 'unique' => 1), 'email' => array('column' => 'email', 'unique' => 0), 'idcity' => array('column' => 'idcity', 'unique' => 0), 'country' => array('column' => 'country_id', 'unique' => 0), 'city' => array('column' => 'city_id', 'unique' => 0), 'lastlogin' => array('column' => 'lastlogin', 'unique' => 0), 'username' => array('column' => 'username', 'unique' => 0), 'region' => array('column' => 'region', 'unique' => 0), 'visinlocation' => array('column' => 'visinlocation', 'unique' => 0), 'accom' => array('column' => 'accom', 'unique' => 0), 'numberguest' => array('column' => 'numberguest', 'unique' => 0), 'staylength_fulltext' => array('column' => 'staylength', 'unique' => 0), 'notifyshould_fulltext' => array('column' => 'notifyshould', 'unique' => 0), 'notifymust_fulltext' => array('column' => 'notifymust', 'unique' => 0), 'username_fulltext' => array('column' => 'username', 'unique' => 0), 'name_fulltext' => array('column' => 'name', 'unique' => 0), 'street_fulltext' => array('column' => 'street', 'unique' => 0), 'languages_fulltext' => array('column' => 'languages', 'unique' => 0), 'hobbies_fulltext' => array('column' => 'hobbies', 'unique' => 0), 'organizations_fulltext' => array('column' => 'organizations', 'unique' => 0), 'travels_fulltext' => array('column' => 'travels', 'unique' => 0), 'attractions_fulltext' => array('column' => 'attractions', 'unique' => 0), 'othcom_fulltext' => array('column' => 'othcom', 'unique' => 0), 'aboutmyself_fulltext' => array('column' => 'aboutmyself', 'unique' => 0), 'offerother_fulltext' => array('column' => 'offerother', 'unique' => 0), 'plans_fulltext' => array('column' => 'plans', 'unique' => 0), 'pets_fulltext' => array('column' => 'pets', 'unique' => 0), 'bigcities_fulltext' => array('column' => 'bigcities', 'unique' => 0), 'chat_MSN_fulltext' => array('column' => 'chat_msn', 'unique' => 0), 'occupation_fulltext' => array('column' => 'occupation', 'unique' => 0), 'chat_SKYPE_fulltext' => array('column' => 'chat_skype', 'unique' => 0)),
		'tableParameters' => array('charset' => 'utf8', 'collate' => 'utf8_general_ci', 'engine' => 'MyISAM')
	);
	var $regions = array(
		'id' => array('type' => 'integer', 'null' => false, 'default' => NULL, 'key' => 'primary'),
		'name' => array('type' => 'string', 'null' => false, 'key' => 'index', 'collate' => 'utf8_general_ci', 'charset' => 'utf8'),
		'created' => array('type' => 'timestamp', 'null' => false, 'default' => 'CURRENT_TIMESTAMP'),
		'updated' => array('type' => 'datetime', 'null' => true, 'default' => NULL),
		'other_names' => array('type' => 'text', 'null' => true, 'default' => NULL, 'collate' => 'utf8_general_ci', 'charset' => 'utf8'),
		'isvalidate' => array('type' => 'integer', 'null' => false, 'default' => '0', 'length' => 2),
		'country_id' => array('type' => 'integer', 'null' => false, 'default' => '0', 'length' => 4, 'key' => 'index'),
		'citiesopen' => array('type' => 'integer', 'null' => false, 'default' => '1', 'length' => 4),
		'selectable' => array('type' => 'boolean', 'null' => true, 'default' => '0', 'key' => 'index'),
		'hcworld_created' => array('type' => 'datetime', 'null' => true, 'default' => NULL),
		'main_city_id' => array('type' => 'integer', 'null' => true, 'default' => NULL),
		'nbmembers' => array('type' => 'integer', 'null' => false, 'default' => '0'),
		'indexes' => array('PRIMARY' => array('column' => 'id', 'unique' => 1), 'country_id' => array('column' => 'country_id', 'unique' => 0), 'name' => array('column' => 'name', 'unique' => 0), 'selectable' => array('column' => 'selectable', 'unique' => 0), 'region_fulltext' => array('column' => array('name', 'other_names'), 'unique' => 0)),
		'tableParameters' => array('charset' => 'utf8', 'collate' => 'utf8_general_ci', 'engine' => 'MyISAM')
	);
}
?>